package constant

const (
	BADGE_ID_BRONZE   = 1
	BADGE_ID_SILVER   = 2
	BADGE_ID_GOLD     = 3
	BADGE_ID_PLATINUM = 4
	BADGE_ID_DIAMOND  = 5
)

const (
	BADGE_LEVEL_BRONZE   = 0
	BADGE_LEVEL_SILVER   = 50
	BADGE_LEVEL_GOLD     = 100
	BADGE_LEVEL_PLATINUM = 200
	BADGE_LEVEL_DIAMOND  = 500
)
