app:
  name: "social-platform-kafka-worker"
  port: 8050

database:
  url:
  username:
  password:
  host:
  port:
  name:
  sslMode:
  timeZone:
  debug: true
  poolSize: 30
  IdleConnTimeoutSeconds: 100
  maxConnAgeSeconds: 3600

kafka:
  brokers:
  topic:
  groupId:
  username:
  password:
  securityProtocol:
  saslMechanism:

email:
  smtpServer:
  smtpPort:
  user:
  password:

log:
  level: "debug"
